services:
  postgres:
    image: postgres:17.2-alpine
    container_name: Postgres_db
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:  				
    build: .
    container_name: FastAPI_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres